-- Auto-generated by db_test/generate_query_ops.py
-- This file assumes db0.account has already been loaded from sql.txt.
USE minisql_db00;

SET @id_eq = 12556789;
SET @balance_eq = 1789;
SET @id_neq = 12556789;
SET @balance_neq = 1789;
SET @name_neq = 'name56789';
SET @range_balance_low = 1200;
SET @range_balance_high = 1210;
SET @balance_gt = 1500;
SET @id_le = 12502000;
SET @update_id = 13056789;
SET @update_balance = 8888;
SET @delete_balance = 1555;
SET @reinsert_id = 14045678;
SET @reinsert_balance = 4567;

SELECT COUNT(*) AS rows_before_queries FROM account;

-- Point queries
select "Part 1: Point Queries" AS "Debug 1"; -- Debug info
SELECT * FROM account WHERE id = @id_eq;
SELECT * FROM account WHERE balance = @balance_eq;

SET @t1_started_at = NOW(6);
SELECT * FROM account WHERE name = 'name56789';
SELECT ROUND(
  TIMESTAMPDIFF(MICROSECOND, @t1_started_at, NOW(6)) / 1000000,
  6
) AS t1_seconds;

SELECT * FROM account WHERE id <> @id_neq;
SELECT * FROM account WHERE balance <> @balance_neq;
SELECT * FROM account WHERE name <> @name_neq;

-- Multi-condition queries and projections
select "Part 2: Multi-condition Queries and Projections" AS "Debug 2"; -- Debug info
SELECT id, name
FROM account
WHERE balance >= @range_balance_low
  AND balance < @range_balance_high;

SELECT name, balance
FROM account
WHERE balance > @balance_gt
  AND id <= @id_le;

SELECT *
FROM account
WHERE id < 12515000
  AND name > 'name14500';

SET @t5_started_at = NOW(6);
SELECT *
FROM account
WHERE id < 12500200
  AND name < 'name00100';
SELECT ROUND(
  TIMESTAMPDIFF(MICROSECOND, @t5_started_at, NOW(6)) / 1000000,
  6
) AS t5_seconds;

-- Unique / primary key conflict checks.
-- The table intentionally starts without UNIQUE(name) so the later index timing is meaningful.
select "Part 3: Unique / primary key conflict checks." AS "Debug 3"; -- Debug info
CREATE UNIQUE INDEX uk_account_name ON account(name);

DELIMITER $$
DROP PROCEDURE IF EXISTS test_account_constraint_conflicts $$
CREATE PROCEDURE test_account_constraint_conflicts()
BEGIN
  DECLARE v_constraint_message TEXT;
  DECLARE CONTINUE HANDLER FOR 1062
  BEGIN
    GET DIAGNOSTICS CONDITION 1 v_constraint_message = MESSAGE_TEXT;
    SELECT v_constraint_message AS constraint_conflict;
  END;

  INSERT INTO account VALUES (12556789, 'dup_pk_probe', 3000);
  INSERT INTO account VALUES (22556789, 'name56789', 3000);
END $$
DELIMITER ;

CALL test_account_constraint_conflicts();
DROP PROCEDURE IF EXISTS test_account_constraint_conflicts;
DROP INDEX uk_account_name ON account;

-- Index create/drop and index effect
select "Part 4: Index create/drop and index effect" AS "Debug 4"; -- Debug info
CREATE INDEX idx01 ON account(name);
ANALYZE TABLE account;

SET @t2_started_at = NOW(6);
SELECT * FROM account WHERE name = 'name56789';
SELECT ROUND(
  TIMESTAMPDIFF(MICROSECOND, @t2_started_at, NOW(6)) / 1000000,
  6
) AS t2_seconds;

SET @t3_started_at = NOW(6);
SELECT * FROM account WHERE name = 'name45678';
SELECT ROUND(
  TIMESTAMPDIFF(MICROSECOND, @t3_started_at, NOW(6)) / 1000000,
  6
) AS t3_seconds;

SET @t6_started_at = NOW(6);
SELECT *
FROM account
WHERE id < 12500200
  AND name < 'name00100';
SELECT ROUND(
  TIMESTAMPDIFF(MICROSECOND, @t6_started_at, NOW(6)) / 1000000,
  6
) AS t6_seconds;

DELETE FROM account WHERE name = 'name45678';
SELECT * FROM account WHERE name = 'name45678';

INSERT INTO account VALUES (@reinsert_id, 'name45678', @reinsert_balance);
SELECT * FROM account WHERE name = 'name45678';

DROP INDEX idx01 ON account;

SET @t4_started_at = NOW(6);
SELECT * FROM account WHERE name = 'name45678';
SELECT ROUND(
  TIMESTAMPDIFF(MICROSECOND, @t4_started_at, NOW(6)) / 1000000,
  6
) AS t4_seconds;

-- Update and verify
select "Part 5: Update and verify" AS "Debug 5"; -- Debug info
UPDATE account
SET id = @update_id,
    balance = @update_balance
WHERE name = 'name56789';

SELECT * FROM account WHERE name = 'name56789';
SELECT * FROM account WHERE id = @update_id;

-- Delete by balance and verify
select "Part 6: Delete by balance and verify" AS "Debug 6"; -- Debug info
DELETE FROM account WHERE balance = @delete_balance;
SELECT * FROM account WHERE balance = @delete_balance;

-- Delete all rows and verify
select "Part 7: Delete all rows and verify" AS "Debug 7"; -- Debug info
DELETE FROM account;
SELECT COUNT(*) AS remaining_rows_after_delete_all FROM account;

-- Drop table and verify
select "Part 8: Drop table and verify" AS "Debug 8"; -- Debug info
DROP TABLE account;
SHOW TABLES;
